name: PVPMoney
version: #VERSION#
description: reward players for killing others
author: Albion
main: de.albionco.pvpmoney.MoneyPlugin
depend: [Vault]
commands:
  pvpmoney:
    description: command to control various aspects of the plugin
    aliases: [pvpm]
permissions:
  pvpmoney.rewards:
    default: true
  pvpmoney.extra:
    default: false
  pvpmoney.admin:
    default: op
  pvpmoney.exempt:
    default: op
