name: PVPMoney
version: 0.7
description: Reward players for PVP kills.
author: charries96
main: com.frostcore.pvpmoney.PVPMoney
softdepend: [Vault]
commands:
  pvpmoney:
    description: PVPMoney administration command.
    aliases: [pvpm]
permissions:
  pvpmoney.rewards:
    default: true
  pvpmoney.admin:
    default: op
  pvpmoney.exempt:
    default: op