name: PVPMoney
version: #VERSION#
description: reward players for killing others
author: Albion
main: de.albionco.pvpmoney.MoneyPlugin
depend: [Vault]
commands:
  pvpmoney:
    description: command to control various aspects of the plugin
    aliases: [pvpm]
permissions:
  pvpmoney.*:
    default: false
    children:
      pvpmoney.basic: true
      pvpmoney.extra: true
      pvpmoney.admin: true
      pvpmoney.exempt: true
  pvpmoney.basic:
    default: true
  pvpmoney.extra:
    default: false
  pvpmoney.exempt:
    default: false
  pvpmoney.admin:
    default: op
